require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HiddenLocationsController do

  # This should return the minimal set of attributes required to create a valid
  # HiddenLocation. As you add validations to HiddenLocation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HiddenLocationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hidden_locations as @hidden_locations" do
      hidden_location = HiddenLocation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hidden_locations).should eq([hidden_location])
    end
  end

  describe "GET show" do
    it "assigns the requested hidden_location as @hidden_location" do
      hidden_location = HiddenLocation.create! valid_attributes
      get :show, {:id => hidden_location.to_param}, valid_session
      assigns(:hidden_location).should eq(hidden_location)
    end
  end

  describe "GET new" do
    it "assigns a new hidden_location as @hidden_location" do
      get :new, {}, valid_session
      assigns(:hidden_location).should be_a_new(HiddenLocation)
    end
  end

  describe "GET edit" do
    it "assigns the requested hidden_location as @hidden_location" do
      hidden_location = HiddenLocation.create! valid_attributes
      get :edit, {:id => hidden_location.to_param}, valid_session
      assigns(:hidden_location).should eq(hidden_location)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HiddenLocation" do
        expect {
          post :create, {:hidden_location => valid_attributes}, valid_session
        }.to change(HiddenLocation, :count).by(1)
      end

      it "assigns a newly created hidden_location as @hidden_location" do
        post :create, {:hidden_location => valid_attributes}, valid_session
        assigns(:hidden_location).should be_a(HiddenLocation)
        assigns(:hidden_location).should be_persisted
      end

      it "redirects to the created hidden_location" do
        post :create, {:hidden_location => valid_attributes}, valid_session
        response.should redirect_to(HiddenLocation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hidden_location as @hidden_location" do
        # Trigger the behavior that occurs when invalid params are submitted
        HiddenLocation.any_instance.stub(:save).and_return(false)
        post :create, {:hidden_location => { "name" => "invalid value" }}, valid_session
        assigns(:hidden_location).should be_a_new(HiddenLocation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HiddenLocation.any_instance.stub(:save).and_return(false)
        post :create, {:hidden_location => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hidden_location" do
        hidden_location = HiddenLocation.create! valid_attributes
        # Assuming there are no other hidden_locations in the database, this
        # specifies that the HiddenLocation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HiddenLocation.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => hidden_location.to_param, :hidden_location => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested hidden_location as @hidden_location" do
        hidden_location = HiddenLocation.create! valid_attributes
        put :update, {:id => hidden_location.to_param, :hidden_location => valid_attributes}, valid_session
        assigns(:hidden_location).should eq(hidden_location)
      end

      it "redirects to the hidden_location" do
        hidden_location = HiddenLocation.create! valid_attributes
        put :update, {:id => hidden_location.to_param, :hidden_location => valid_attributes}, valid_session
        response.should redirect_to(hidden_location)
      end
    end

    describe "with invalid params" do
      it "assigns the hidden_location as @hidden_location" do
        hidden_location = HiddenLocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HiddenLocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => hidden_location.to_param, :hidden_location => { "name" => "invalid value" }}, valid_session
        assigns(:hidden_location).should eq(hidden_location)
      end

      it "re-renders the 'edit' template" do
        hidden_location = HiddenLocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HiddenLocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => hidden_location.to_param, :hidden_location => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hidden_location" do
      hidden_location = HiddenLocation.create! valid_attributes
      expect {
        delete :destroy, {:id => hidden_location.to_param}, valid_session
      }.to change(HiddenLocation, :count).by(-1)
    end

    it "redirects to the hidden_locations list" do
      hidden_location = HiddenLocation.create! valid_attributes
      delete :destroy, {:id => hidden_location.to_param}, valid_session
      response.should redirect_to(hidden_locations_url)
    end
  end

end
