require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StudyCoursesController do

  # This should return the minimal set of attributes required to create a valid
  # StudyCourse. As you add validations to StudyCourse, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StudyCoursesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all study_courses as @study_courses" do
      study_course = StudyCourse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:study_courses).should eq([study_course])
    end
  end

  describe "GET show" do
    it "assigns the requested study_course as @study_course" do
      study_course = StudyCourse.create! valid_attributes
      get :show, {:id => study_course.to_param}, valid_session
      assigns(:study_course).should eq(study_course)
    end
  end

  describe "GET new" do
    it "assigns a new study_course as @study_course" do
      get :new, {}, valid_session
      assigns(:study_course).should be_a_new(StudyCourse)
    end
  end

  describe "GET edit" do
    it "assigns the requested study_course as @study_course" do
      study_course = StudyCourse.create! valid_attributes
      get :edit, {:id => study_course.to_param}, valid_session
      assigns(:study_course).should eq(study_course)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StudyCourse" do
        expect {
          post :create, {:study_course => valid_attributes}, valid_session
        }.to change(StudyCourse, :count).by(1)
      end

      it "assigns a newly created study_course as @study_course" do
        post :create, {:study_course => valid_attributes}, valid_session
        assigns(:study_course).should be_a(StudyCourse)
        assigns(:study_course).should be_persisted
      end

      it "redirects to the created study_course" do
        post :create, {:study_course => valid_attributes}, valid_session
        response.should redirect_to(StudyCourse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved study_course as @study_course" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudyCourse.any_instance.stub(:save).and_return(false)
        post :create, {:study_course => { "name" => "invalid value" }}, valid_session
        assigns(:study_course).should be_a_new(StudyCourse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudyCourse.any_instance.stub(:save).and_return(false)
        post :create, {:study_course => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested study_course" do
        study_course = StudyCourse.create! valid_attributes
        # Assuming there are no other study_courses in the database, this
        # specifies that the StudyCourse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StudyCourse.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => study_course.to_param, :study_course => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested study_course as @study_course" do
        study_course = StudyCourse.create! valid_attributes
        put :update, {:id => study_course.to_param, :study_course => valid_attributes}, valid_session
        assigns(:study_course).should eq(study_course)
      end

      it "redirects to the study_course" do
        study_course = StudyCourse.create! valid_attributes
        put :update, {:id => study_course.to_param, :study_course => valid_attributes}, valid_session
        response.should redirect_to(study_course)
      end
    end

    describe "with invalid params" do
      it "assigns the study_course as @study_course" do
        study_course = StudyCourse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudyCourse.any_instance.stub(:save).and_return(false)
        put :update, {:id => study_course.to_param, :study_course => { "name" => "invalid value" }}, valid_session
        assigns(:study_course).should eq(study_course)
      end

      it "re-renders the 'edit' template" do
        study_course = StudyCourse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudyCourse.any_instance.stub(:save).and_return(false)
        put :update, {:id => study_course.to_param, :study_course => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested study_course" do
      study_course = StudyCourse.create! valid_attributes
      expect {
        delete :destroy, {:id => study_course.to_param}, valid_session
      }.to change(StudyCourse, :count).by(-1)
    end

    it "redirects to the study_courses list" do
      study_course = StudyCourse.create! valid_attributes
      delete :destroy, {:id => study_course.to_param}, valid_session
      response.should redirect_to(study_courses_url)
    end
  end

end
